version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory-management-app
    container_name: inventory-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:GENERATE_YOUR_KEY
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventory
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inventory-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

