version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory-management-app
    container_name: inventory-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:GENERATE_YOUR_KEY
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
