services:
  inventory-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory-management-app
    container_name: inventory-app
    restart: unless-stopped
    working_dir: /var/www/code
    volumes:
      - ./code:/var/www/code
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5502
      - DB_DATABASE=inventory
      - DB_USERNAME=admin
      - DB_PASSWORD=katasandi
    depends_on:
      - db
  db:
    image: postgres:17.0
    container_name: inventory-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: katasandi
      POSTGRES_DB: inventory
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5502:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  postgres_data: